camunda.bpm:
  admin-user:
    id: kermit
    password: superSecret
    firstName: Kermit
  filter:
    create: All tasks
  database:
    type: postgres

server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:30000/camunda
    username: postgres
    password: postgres
#    initialization-mode: always
    driver-class-name: org.postgresql.Driver